// Shared AI provider catalog used by the Settings drawer and the app.
export const PROVIDERS = [
  {
    id: 'anthropic',
    name: 'Claude',
    emoji: '🟠',
    needsKey: true,
    keyHint: 'sk-ant-...',
    keyUrl: 'https://console.anthropic.com/settings/keys',
    models: ['claude-sonnet-4-6', 'claude-opus-4-8', 'claude-haiku-4-5-20251001'],
    note: 'Best subtask quality.',
  },
  {
    id: 'openai',
    name: 'GPT',
    emoji: '🟢',
    needsKey: true,
    keyHint: 'sk-...',
    keyUrl: 'https://platform.openai.com/api-keys',
    models: ['gpt-5.5', 'gpt-5.4-mini', 'gpt-5.4-nano', 'gpt-4o-mini'],
    note: 'Most people already have a key.',
  },
  {
    id: 'gemini',
    name: 'Gemini',
    emoji: '🔵',
    needsKey: true,
    keyHint: 'AIza...',
    keyUrl: 'https://aistudio.google.com/apikey',
    models: ['gemini-3.5-flash', 'gemini-3.1-pro-preview', 'gemini-3.1-flash-lite', 'gemini-2.0-flash'],
    note: 'Generous free tier.',
  },
  {
    id: 'groq',
    name: 'Groq',
    emoji: '⚡',
    needsKey: true,
    keyHint: 'gsk_...',
    keyUrl: 'https://console.groq.com/keys',
    models: ['openai/gpt-oss-120b', 'openai/gpt-oss-20b', 'llama-3.3-70b-versatile'],
    note: 'Free and very fast.',
  },
  {
    id: 'ollama',
    name: 'Ollama',
    emoji: '🦙',
    needsKey: false,
    local: true,
    models: ['llama3.2', 'qwen2.5', 'mistral'],
    note: 'Runs fully on your machine. No key, fully private.',
  },
  {
    id: 'codex',
    name: 'Codex CLI',
    emoji: '🤖',
    needsKey: false,
    local: true,
    models: [],
    note: 'Uses your local Codex login. No key. Local copy only.',
  },
];

export const getProvider = (id) => PROVIDERS.find((p) => p.id === id);
